# Generated by Django 5.0.1 on 2025-05-13 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_emailopen_link_linkclick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('subscription', 'New Subscription'), ('abandoned_cart', 'Abandoned Cart'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('inactivity', 'Inactivity'), ('purchase', 'Purchase'), ('custom', 'Custom Event')], max_length=50)),
                ('trigger_details', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('step_type', models.CharField(choices=[('email', 'Send Email'), ('wait', 'Wait Period'), ('condition', 'Condition Check'), ('action', 'Custom Action')], max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(default=dict)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='marketing.automation')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
